# https://golangci-lint.run/usage/configuration/
# Golang CI configurations
run:
  timeout: 5m

# linters settings

# output configuration options
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  #
  # Multiple can be specified by separating them by comma, output can be provided
  # for each of them by separating format name and path by colon symbol.
  # Output path can be either `stdout`, `stderr` or path to the file to write to.
  # Example: "checkstyle:report.json,colored-line-number"
  #
  # Default: colored-line-number
  format: "colored-line-number,github-actions,checkstyle:./reports/golangci-lint.xml"
  sort-results: true
